name: 'web_shop_orders'
version: '1.0.0'
config-version: 2

profile: 'web_shop_orders'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
    "dbt_date:time_zone": "Europe/Amsterdam"

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  web_shop_orders:
    +materialized: table
    staging:
      +materialized: view
